export const data3 = {
    "reportType": "NO_PASSING_ROUTE_GRAPHICAL_REPORT_IFRAME",
    "agency": {
        "agencyName": "Ohio Department of Transportation - District 09"
    },
    "orderBy": {
        "orderedBy": "Route"
    },
    "sortOrder": "Route",
    "ctrlPtBegin": "0",
    "ctrlPtEnd": "12.7",
    "routeFilter": " where route.client_id=97 and route.rtecode IN ( select distinct NPZone.rtecode from NPZone where NPZone.client_id=97 and  NPZone.rtecode  IN ('480') AND NPZone.study_type  IN ('Current') AND (NPZone.b_trulog  BETWEEN 0  AND 12.7   OR NPZone.e_trulog  BETWEEN 0  AND 12.7  ) AND (NPZone.e_trulog  BETWEEN 0  AND 12.7   OR NPZone.b_trulog  BETWEEN 0  AND 12.7  ))",
    "pendingWhereQuery": "",
    "controlFilter": " c.log_point BETWEEN 0 AND 12.7 ",
    "noPassFilter": "where  NPZone.rtecode  IN ('480') AND NPZone.study_type  IN ('Current') AND (NPZone.b_trulog  BETWEEN 0  AND 12.7   OR NPZone.e_trulog  BETWEEN 0  AND 12.7  ) AND (NPZone.e_trulog  BETWEEN 0  AND 12.7   OR NPZone.b_trulog  BETWEEN 0  AND 12.7  )",
    "scaleSize": 1000,
    "controlsArr": [
        {
            "GroupLabel": "00763",
            "children": [
                {
                    "Type": "Intersection",
                    "ctrl_id": 11662,
                    "descript": "SR 00041 SR-41",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": "142.590885",
                    "gps_lat": "38.671975729",
                    "gps_lon": "-83.750604183",
                    "log_point": "0.000",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": "1736182808650",
                    "upduser": null
                },
                {
                    "Type": "Mile Marker",
                    "ctrl_id": 44264,
                    "descript": "MILE MARKER 0",
                    "dict_type": "29",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": "140.491358",
                    "gps_lat": "38.672347136",
                    "gps_lon": "-83.750493915",
                    "log_point": "0.027",
                    "max_log_point": null,
                    "memcontrol": "",
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Right",
                    "survey_dte": "1736182910265",
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11665,
                    "descript": "TR 00563 SLICKAWAY RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "0.152",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42136,
                    "descript": "BEGIN BRIDGE: 0803766",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "0.156",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 43326,
                    "descript": "END BRIDGE: 0803766",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "0.170",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11667,
                    "descript": "TR 00251 STRINGTOWN RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "0.336",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 41499,
                    "descript": "BEGIN BRIDGE: 0803774",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "0.555",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42689,
                    "descript": "END BRIDGE: 0803774",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "0.565",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 41956,
                    "descript": "BEGIN BRIDGE: 0803813",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "0.936",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 43146,
                    "descript": "END BRIDGE: 0803813",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "0.938",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 41330,
                    "descript": "BEGIN BRIDGE: 0803848",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "0.986",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42520,
                    "descript": "END BRIDGE: 0803848",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "1.007",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11669,
                    "descript": "TR 00350 LAWWILL RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "1.336",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 41378,
                    "descript": "BEGIN BRIDGE: 0803987",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "1.339",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42568,
                    "descript": "END BRIDGE: 0803987",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "1.343",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 41597,
                    "descript": "BEGIN BRIDGE: 0803901",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "1.472",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42787,
                    "descript": "END BRIDGE: 0803901",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "1.476",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11670,
                    "descript": "CR 00031 MARTIN HILL RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "1.494",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11673,
                    "descript": "TR 00246 FORK RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "2.231",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 41684,
                    "descript": "BEGIN BRIDGE: 0803898",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "2.826",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42874,
                    "descript": "END BRIDGE: 0803898",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "2.828",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42168,
                    "descript": "BEGIN BRIDGE: 0803944",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "4.120",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 43358,
                    "descript": "END BRIDGE: 0803944",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "4.122",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 41199,
                    "descript": "BEGIN BRIDGE: 0803952",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "4.144",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42389,
                    "descript": "END BRIDGE: 0803952",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "4.161",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11674,
                    "descript": "CR 00049 SCOFFIELD RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "4.186",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11676,
                    "descript": "CR 00063 BRADYSVILLE RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "4.444",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11679,
                    "descript": "TR 00241 BRUSHY FORK RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "6.093",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 41582,
                    "descript": "BEGIN BRIDGE: 0804002",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "6.094",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42772,
                    "descript": "END BRIDGE: 0804002",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "6.111",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11680,
                    "descript": "CR 00235 HICKORY RIDGE RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "6.752",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11682,
                    "descript": "TR 00235 HICKORY RIDGE RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "6.752",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 41278,
                    "descript": "BEGIN BRIDGE: 0804045",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "8.135",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42468,
                    "descript": "END BRIDGE: 0804045",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "8.155",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11683,
                    "descript": "CR 00106 SUCK RUN RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "8.170",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42176,
                    "descript": "BEGIN BRIDGE: 0804096",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "8.199",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 43366,
                    "descript": "END BRIDGE: 0804096",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "8.245",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11686,
                    "descript": "TR 00031 WILES RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "8.284",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11687,
                    "descript": "CR 00019 CHICKEN HOLLOW RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "8.705",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 41801,
                    "descript": "BEGIN BRIDGE: 0804134",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "9.841",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42991,
                    "descript": "END BRIDGE: 0804134",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "9.876",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11689,
                    "descript": "CR 00102 HUFF HILL RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "9.887",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11692,
                    "descript": "TR 00024 FORK RD",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "10.452",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 41497,
                    "descript": "BEGIN BRIDGE: 0804150",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "11.429",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42687,
                    "descript": "END BRIDGE: 0804150",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "11.432",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 41885,
                    "descript": "BEGIN BRIDGE: 0804169",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "11.510",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 43075,
                    "descript": "END BRIDGE: 0804169",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "11.513",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 41450,
                    "descript": "BEGIN BRIDGE: 0804215",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "11.835",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Bridge",
                    "ctrl_id": 42640,
                    "descript": "END BRIDGE: 0804215",
                    "dict_type": "2",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "11.838",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": "Both",
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11693,
                    "descript": "SR 00353 SR-353",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "12.674",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                },
                {
                    "Type": "Intersection",
                    "ctrl_id": 11695,
                    "descript": "SR 00125 SR-125",
                    "dict_type": "10",
                    "dir_route": "0",
                    "effdate": null,
                    "endeffdate": null,
                    "gps_alt": null,
                    "gps_lat": null,
                    "gps_lon": null,
                    "log_point": "12.700",
                    "max_log_point": null,
                    "memcontrol": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "side": null,
                    "survey_dte": null,
                    "upduser": null
                }
            ]
        }
    ],
    "npZonesArr": [
        {
            "GroupLabel": "00763",
            "children": [
                {
                    "NPZoneKey": 5155,
                    "b_trulog": 0,
                    "beg_alt": "142.59088500000000",
                    "beg_lat": "38.67197805717204",
                    "beg_lon": "-83.75061054026887",
                    "dir_route": "0",
                    "e_trulog": 0.005,
                    "effdate": "1736160080747",
                    "end_alt": "142.47593200000000",
                    "end_lat": "38.67205259919967",
                    "end_lon": "-83.75059641599067",
                    "endeffdate": null,
                    "max_log_point": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "s_date": "1736160080747",
                    "study_type": "Current",
                    "upduser": null,
                    "zone_code": "06",
                    "zone_orig": "T"
                },
                {
                    "NPZoneKey": 5156,
                    "b_trulog": 0.005,
                    "beg_alt": "142.47593200000000",
                    "beg_lat": "38.67205259919967",
                    "beg_lon": "-83.75059641599067",
                    "dir_route": "0",
                    "e_trulog": 0.162,
                    "effdate": "1736160080747",
                    "end_alt": "125.05099700000000",
                    "end_lat": "38.67268865973717",
                    "end_lon": "-83.74808747284150",
                    "endeffdate": null,
                    "max_log_point": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "s_date": "1736160080747",
                    "study_type": "Current",
                    "upduser": null,
                    "zone_code": "07",
                    "zone_orig": "T"
                },
                {
                    "NPZoneKey": 5157,
                    "b_trulog": 0.005,
                    "beg_alt": "142.47593200000000",
                    "beg_lat": "38.67205190879992",
                    "beg_lon": "-83.75058240000932",
                    "dir_route": "0",
                    "e_trulog": 0.162,
                    "effdate": "1736160080747",
                    "end_alt": "125.05099700000000",
                    "end_lat": "38.67267909826273",
                    "end_lon": "-83.74808059915851",
                    "endeffdate": null,
                    "max_log_point": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "s_date": "1736160080747",
                    "study_type": "Current",
                    "upduser": null,
                    "zone_code": "08",
                    "zone_orig": "T"
                },
                {
                    "NPZoneKey": 5158,
                    "b_trulog": 0.162,
                    "beg_alt": "125.05099700000000",
                    "beg_lat": "38.67268865973717",
                    "beg_lon": "-83.74808747284150",
                    "dir_route": "0",
                    "e_trulog": 0.173,
                    "effdate": "1736160080747",
                    "end_alt": "123.86764400000000",
                    "end_lat": "38.67280425652224",
                    "end_lon": "-83.74793473196824",
                    "endeffdate": null,
                    "max_log_point": null,
                    "min_log_point": null,
                    "name": "SBROSR00763^^C",
                    "npProjectTitle": null,
                    "record_inserted": 0,
                    "record_updated": 0,
                    "route": "00763",
                    "rtecode": "480",
                    "s_date": "1736160080747",
                    "study_type": "Current",
                    "upduser": null,
                    "zone_code": "06",
                    "zone_orig": "T"
                }
            ]
        }
    ],
    "noPassTypes": [
        {
            "descript": "TWLTL"
        },
        {
            "descript": "2 DBYL"
        },
        {
            "descript": "LTL SAME"
        },
        {
            "descript": "LTL Opp"
        },
        {
            "descript": "---------"
        },
        {
            "descript": "None"
        },
        {
            "descript": "L No Pass"
        },
        {
            "descript": "R No Pass"
        },
        {
            "descript": "L Pass"
        },
        {
            "descript": "R Pass"
        },
        {
            "descript": "Excluded"
        },
        {
            "descript": "Undetermined"
        }
    ],
    "routesArr": [
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SADASR00041^^C",
            "Primary1": "D9",
            "Route": "00041",
            "RouteCode": "208",
            "RouteType": "Major Standard Rural",
            "Secondary": "Adams",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SADASR00073^^C",
            "Primary1": "D9",
            "Route": "00073",
            "RouteCode": "290",
            "RouteType": "Major Standard Rural",
            "Secondary": "Adams",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SADASR00348^^C",
            "Primary1": "D9",
            "Route": "00348",
            "RouteCode": "456",
            "RouteType": "Major Standard Rural",
            "Secondary": "Adams",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SADASR00770^^C",
            "Primary1": "D9",
            "Route": "00770",
            "RouteCode": "481",
            "RouteType": "Major Standard Rural",
            "Secondary": "Adams",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SADASR00781^^C",
            "Primary1": "D9",
            "Route": "00781",
            "RouteCode": "493",
            "RouteType": "Standard Rural",
            "Secondary": "Adams",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SADAUS00052^^C",
            "Primary1": "D9",
            "Route": "00052",
            "RouteCode": "246",
            "RouteType": "Major Standard Rural",
            "Secondary": "Adams",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SBROSR00041^^C",
            "Primary1": "D9",
            "Route": "00041",
            "RouteCode": "210",
            "RouteType": "Major Standard Rural",
            "Secondary": "Brown",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SBROSR00123^^C",
            "Primary1": "D9",
            "Route": "00123",
            "RouteCode": "349",
            "RouteType": "Major Standard Rural",
            "Secondary": "Brown",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SBROSR00221^^C",
            "Primary1": "D9",
            "Route": "00221",
            "RouteCode": "435",
            "RouteType": "Major Standard Rural",
            "Secondary": "Brown",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SBROSR00505^^C",
            "Primary1": "D9",
            "Route": "00505",
            "RouteCode": "465",
            "RouteType": "Major Standard Rural",
            "Secondary": "Brown",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SBROSR00756^^C",
            "Primary1": "D9",
            "Route": "00756",
            "RouteCode": "479",
            "RouteType": "Major Standard Rural",
            "Secondary": "Brown",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": null,
            "DirectionIndex": "0",
            "Name": "SBROSR00763^^C",
            "Primary1": "D9",
            "Route": "00763",
            "RouteCode": "480",
            "RouteType": "Standard Rural",
            "Secondary": "Brown",
            "Tertiary": null
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SBROSR00774^^C",
            "Primary1": "D9",
            "Route": "00774",
            "RouteCode": "488",
            "RouteType": "Major Standard Rural",
            "Secondary": "Brown",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SBROUS00052^^C",
            "Primary1": "D9",
            "Route": "00052",
            "RouteCode": "247",
            "RouteType": "Major Standard Rural",
            "Secondary": "Brown",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SHIGSR00028^^C",
            "Primary1": "D9",
            "Route": "00028",
            "RouteCode": "147",
            "RouteType": "Major Standard Rural",
            "Secondary": "Highland",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SHIGSR00124^^C",
            "Primary1": "D9",
            "Route": "00124",
            "RouteCode": "352",
            "RouteType": "Major Standard Rural",
            "Secondary": "Highland",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": null,
            "DirectionIndex": "0",
            "Name": "SHIGSR00134^^C",
            "Primary1": "D9",
            "Route": "00134",
            "RouteCode": "371",
            "RouteType": "Standard Rural",
            "Secondary": "Highland",
            "Tertiary": null
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SHIGSR00753^^C",
            "Primary1": "D9",
            "Route": "00753",
            "RouteCode": "478",
            "RouteType": "Major Standard Rural",
            "Secondary": "Highland",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SHIGSR00771^^C",
            "Primary1": "D9",
            "Route": "00771",
            "RouteCode": "482",
            "RouteType": "Major Standard Rural",
            "Secondary": "Highland",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SHIGSR00785^^C",
            "Primary1": "D9",
            "Route": "00785",
            "RouteCode": "494",
            "RouteType": "Major Standard Rural",
            "Secondary": "Highland",
            "Tertiary": "CNT"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SJACSR00093^^C",
            "Primary1": "D9",
            "Route": "00093",
            "RouteCode": "316",
            "RouteType": "Major Standard Rural",
            "Secondary": "Jackson",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SJACSR00124^^C",
            "Primary1": "D9",
            "Route": "00124",
            "RouteCode": "353",
            "RouteType": "Major Standard Rural",
            "Secondary": "Jackson",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SJACSR00139^^C",
            "Primary1": "D9",
            "Route": "00139",
            "RouteCode": "382",
            "RouteType": "Major Standard Rural",
            "Secondary": "Jackson",
            "Tertiary": "RRN"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SJACSR00140^^C",
            "Primary1": "D9",
            "Route": "00140",
            "RouteCode": "385",
            "RouteType": "Major Standard Rural",
            "Secondary": "Jackson",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SJACSR00233^^C",
            "Primary1": "D9",
            "Route": "00233",
            "RouteCode": "436",
            "RouteType": "Major Standard Rural",
            "Secondary": "Jackson",
            "Tertiary": "NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SJACSR00327^^C",
            "Primary1": "D9",
            "Route": "00327",
            "RouteCode": "451",
            "RouteType": "Major Standard Rural",
            "Secondary": "Jackson",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SJACSR00776^^C",
            "Primary1": "D9",
            "Route": "00776",
            "RouteCode": "490",
            "RouteType": "Major Standard Rural",
            "Secondary": "Jackson",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SJACSR00788^^C",
            "Primary1": "D9",
            "Route": "00788",
            "RouteCode": "495",
            "RouteType": "Major Standard Rural",
            "Secondary": "Jackson",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SLAWSR00093^^C",
            "Primary1": "D9",
            "Route": "00093",
            "RouteCode": "318",
            "RouteType": "Major Standard Rural",
            "Secondary": "Lawrence",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SLAWSR00217^^C",
            "Primary1": "D9",
            "Route": "00217",
            "RouteCode": "432",
            "RouteType": "Major Standard Rural",
            "Secondary": "Lawrence",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SLAWSR00218^^C",
            "Primary1": "D9",
            "Route": "00218",
            "RouteCode": "433",
            "RouteType": "Major Standard Rural",
            "Secondary": "Lawrence",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SLAWSR00378^^C",
            "Primary1": "D9",
            "Route": "00378",
            "RouteCode": "464",
            "RouteType": "Major Standard Rural",
            "Secondary": "Lawrence",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SLAWSR00775^^C",
            "Primary1": "D9",
            "Route": "00775",
            "RouteCode": "489",
            "RouteType": "Major Standard Rural",
            "Secondary": "Lawrence",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SLAWSR00790^^C",
            "Primary1": "D9",
            "Route": "00790",
            "RouteCode": "496",
            "RouteType": "Major Standard Rural",
            "Secondary": "Lawrence",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": null,
            "DirectionIndex": "0",
            "Name": "SPIKSR00124^^C",
            "Primary1": "D9",
            "Route": "00124",
            "RouteCode": "354",
            "RouteType": "Standard Rural",
            "Secondary": "Pike",
            "Tertiary": null
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SPIKSR00776^^C",
            "Primary1": "D9",
            "Route": "00776",
            "RouteCode": "491",
            "RouteType": "Major Standard Rural",
            "Secondary": "Pike",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SROSSR00028^^C",
            "Primary1": "D9",
            "Route": "00028",
            "RouteCode": "151",
            "RouteType": "Major Standard Rural",
            "Secondary": "Ross",
            "Tertiary": null
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SROSSR00159^^C",
            "Primary1": "D9",
            "Route": "00159",
            "RouteCode": "411",
            "RouteType": "Major Standard Rural",
            "Secondary": "Ross",
            "Tertiary": "NPZ"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SROSSR00180^^C",
            "Primary1": "D9",
            "Route": "00180",
            "RouteCode": "428",
            "RouteType": "Major Standard Rural",
            "Secondary": "Ross",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SROSSR00327^^C",
            "Primary1": "D9",
            "Route": "00327",
            "RouteCode": "453",
            "RouteType": "Major Standard Rural",
            "Secondary": "Ross",
            "Tertiary": "NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SROSSR00772^^C",
            "Primary1": "D9",
            "Route": "00772",
            "RouteCode": "486",
            "RouteType": "Major Standard Rural",
            "Secondary": "Ross",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": "PORTION OF ROAD MARKED UNDERTRIMED DUE TO NEW PAVMENT ON RIGHT SIDE OF THE ROAD",
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SROSUS00050^^C",
            "Primary1": "D9",
            "Route": "00050",
            "RouteCode": "242",
            "RouteType": "Major Standard Rural",
            "Secondary": "Ross",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SSCISR00104^^C",
            "Primary1": "D9",
            "Route": "00104",
            "RouteCode": "334",
            "RouteType": "Major Standard Rural",
            "Secondary": "Scioto",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SSCISR00125^^C",
            "Primary1": "D9",
            "Route": "00125",
            "RouteCode": "358",
            "RouteType": "Major Standard Rural",
            "Secondary": "Scioto",
            "Tertiary": "NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SSCISR00139^^C",
            "Primary1": "D9",
            "Route": "00139",
            "RouteCode": "383",
            "RouteType": "Major Standard Rural",
            "Secondary": "Scioto",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SSCISR00239^^C",
            "Primary1": "D9",
            "Route": "00239",
            "RouteCode": "438",
            "RouteType": "Major Standard Rural",
            "Secondary": "Scioto",
            "Tertiary": "NPZ"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SSCISR00348^^C",
            "Primary1": "D9",
            "Route": "00348",
            "RouteCode": "457",
            "RouteType": "Major Standard Rural",
            "Secondary": "Scioto",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SSCISR00728^^C",
            "Primary1": "D9",
            "Route": "00728",
            "RouteCode": "477",
            "RouteType": "Major Standard Rural",
            "Secondary": "Scioto",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SSCISR00772^^C",
            "Primary1": "D9",
            "Route": "00772",
            "RouteCode": "487",
            "RouteType": "Major Standard Rural",
            "Secondary": "Scioto",
            "Tertiary": "RRN"
        },
        {
            "Comments": null,
            "Direction": "East",
            "DirectionIndex": "3",
            "Name": "SSCISR00776^^C",
            "Primary1": "D9",
            "Route": "00776",
            "RouteCode": "492",
            "RouteType": "Major Standard Rural",
            "Secondary": "Scioto",
            "Tertiary": "CNT/NPZ"
        },
        {
            "Comments": null,
            "Direction": "North",
            "DirectionIndex": "1",
            "Name": "SSCISR00852^^C",
            "Primary1": "D9",
            "Route": "00852",
            "RouteCode": "500",
            "RouteType": "Major Standard Rural",
            "Secondary": "Scioto",
            "Tertiary": "CNT/NPZ"
        }
    ],
    "routesNumArr": [
        {
            "route": "00007"
        },
        {
            "route": "00023"
        },
        {
            "route": "00028"
        },
        {
            "route": "00041"
        },
        {
            "route": "00050"
        },
        {
            "route": "00052"
        },
        {
            "route": "00062"
        },
        {
            "route": "00068"
        },
        {
            "route": "00072"
        },
        {
            "route": "00073"
        },
        {
            "route": "00093"
        },
        {
            "route": "00104"
        },
        {
            "route": "00123"
        },
        {
            "route": "00124"
        },
        {
            "route": "00125"
        },
        {
            "route": "00131"
        },
        {
            "route": "00134"
        },
        {
            "route": "00135"
        },
        {
            "route": "00136"
        },
        {
            "route": "00137"
        },
        {
            "route": "00138"
        },
        {
            "route": "00139"
        },
        {
            "route": "00140"
        },
        {
            "route": "00141"
        },
        {
            "route": "00159"
        },
        {
            "route": "00180"
        },
        {
            "route": "00207"
        },
        {
            "route": "00217"
        },
        {
            "route": "00218"
        },
        {
            "route": "00220"
        },
        {
            "route": "00221"
        },
        {
            "route": "00233"
        },
        {
            "route": "00239"
        },
        {
            "route": "00243"
        },
        {
            "route": "00247"
        },
        {
            "route": "00251"
        },
        {
            "route": "00253"
        },
        {
            "route": "00279"
        },
        {
            "route": "00286"
        },
        {
            "route": "00321"
        },
        {
            "route": "00327"
        },
        {
            "route": "00335"
        },
        {
            "route": "00348"
        },
        {
            "route": "00353"
        },
        {
            "route": "00371"
        },
        {
            "route": "00372"
        },
        {
            "route": "00373"
        },
        {
            "route": "00378"
        },
        {
            "route": "00505"
        },
        {
            "route": "00506"
        },
        {
            "route": "00522"
        },
        {
            "route": "00527"
        },
        {
            "route": "00551"
        },
        {
            "route": "00552"
        },
        {
            "route": "00650"
        },
        {
            "route": "00728"
        },
        {
            "route": "00753"
        },
        {
            "route": "00756"
        },
        {
            "route": "00763"
        },
        {
            "route": "00770"
        },
        {
            "route": "00771"
        },
        {
            "route": "00772"
        },
        {
            "route": "00774"
        },
        {
            "route": "00775"
        },
        {
            "route": "00776"
        },
        {
            "route": "00781"
        },
        {
            "route": "00785"
        },
        {
            "route": "00788"
        },
        {
            "route": "00790"
        },
        {
            "route": "00823"
        },
        {
            "route": "00852"
        }
    ],
    "studyType": "Current",
    "stripeGapRatio": {
        "stripeLen": 10,
        "gapLen": 30
    }
}